mail_address: usertest_onePop@yopmail.com
config_yaml: /shared/mfs/data/home/croux/scratch/test/ABConline/one_pop/test_onePop_v10.yaml
timeStamp: testOnePopV10 
infile: /shared/home/croux/scratch/test/ABConline/reduced_fastaFile.fasta
region: coding
nspecies: 1
nameA: flo
nameOutgroup: NA
max_N_tolerated: 0.05
Lmin: 100
nMin: 18
mu: 0.000000003
rho_over_theta: 0.8
N_min: 100
N_max: 5000000
Tchanges_min: 100
Tchanges_max: 500000
